name: CI - Frontend

on:
  push:
    branches: [ frontend ]
  pull_request:
    branches: [ frontend ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Installer les dépendances
        run: npm install

      - name: Build de l'application React
        run: npm run build
