name: CI - Backend

on:
  push:
    branches: [ backend ]
  pull_request:
    branches: [ backend ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Cloner le repo
        uses: actions/checkout@v3

      - name: Installer Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Installer les dépendances
        run: npm install

      - name: Lancer les tests (optionnel)
        run: npm run test || echo "Aucun test défini"
